name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Build
      run: make
    - name: Test Run (optional)
      run: ./laptop_recommender < input.txt || true
